apiVersion: v1
kind: Service
metadata:
  name: hermes-service
spec:
  type:
    NodePort
  selector:
    app: hermes
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30200
